export {default as Footer} from "./Footer"
export {default as Section_one} from "./Section_one"
export {default as Section_two} from "./Section_two"
export {default as Section_three} from "./Section_three"
export {default as Section_four} from "./Section_four"
export {default as Navbar} from "./Navbar"